version: '3.4'

services:
  personalaccountant:
    image: ${DOCKER_REGISTRY-}personalaccountant
    environment:
      ConnectionStrings__DefaultConnection: Server=database;Database=master;User=sa;Password=GW9nFvT4FXDymRAGQnXvFkEmqDuGd7tF;MultipleActiveResultSets=true
    build:
      context: .
      dockerfile: PersonalAccountant/Dockerfile
    depends_on:
      - database

  database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "GW9nFvT4FXDymRAGQnXvFkEmqDuGd7tF"
      ACCEPT_EULA: "Y"